version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.8 
    steps:
      - checkout
      - run: sudo python3 -m pip install -r requirements.txt
      - run: sudo apt-get update
      - run: sudo apt-get install git-annex
      # cache the installed libraries
      - save_cache:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }} 
          paths:
            - "/usr/local/bin" 
            - "/usr/local/lib/python3.6/site-packages"

  test-sklearn:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      # use the saved cache from the build to avoid reinstalling the libs
      - run: sudo chown -R circleci /usr
      - restore_cache:
          keys:
            - pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: pip install sklearn
      - run:
          name: sklearn
          command: pytest ./tests/test_sklearn.py

workflows:
  version: 2
  tests:
    jobs:
      - build
      - test-sklearn:
          requires:
            - build
