version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.8 
    steps:
      - checkout
      # cache the installed libraries
      - run: sudo python -m pip install -r requirements.txt
      - save_cache:
          key: pip-packages-v11-{{ .Branch }}-{{ checksum "requirements.txt" }} 
          paths:
            - "/usr/local/bin" 
            - "/usr/local/lib/python3.6/site-packages"

  test-sklearn:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo chown -R circleci /usr/local
      # use the saved cache from the build to avoid reinstalling the libs
      - restore_cache:
          keys:
            - pip-packages-v11-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: sudo python -m pip install sklearn
      - run:
          name: sklearn
          command: pytest ./tests/test_sklearn.py

  test-datalad:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo apt-get update
      # install git-annex-standalone https://git-annex.branchable.com/install/
      # following informations from http://neuro.debian.net/  
      - run: wget -O- http://neuro.debian.net/lists/stretch.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
      # https://github.com/jacobalberty/unifi-docker/issues/64
      - run: sudo apt-key adv --recv-keys --keyserver hkp://ipv4.pool.sks-keyservers.net:80 0xA5D32F012649A5A9
      - run: sudo apt-get update
      - run: sudo apt-get install git-annex-standalone
      - run: sudo chown -R circleci /usr/local
      # use the saved cache from the build to avoid reinstalling the libs
      - restore_cache:
          keys:
            - pip-packages-v11-{{ .Branch }}-{{ checksum "requirements.txt" }}
      
      - run:
          name: datalad
          command: pytest ./tests/test_datalad.py

  test-gzip:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo chown -R circleci /usr/local
      # use the saved cache from the build to avoid reinstalling the libs
      - restore_cache:
          keys:
            - pip-packages-v11-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: gzip
          command: pytest ./tests/test_gzip.py

  test-multiple:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo chown -R circleci /usr/local
      # use the saved cache from the build to avoid reinstalling the libs
      - restore_cache:
          keys:
            - pip-packages-v11-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: multiple
          command: pytest ./tests/test_multiple.py

  test-url:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo chown -R circleci /usr/local
      # use the saved cache from the build to avoid reinstalling the libs
      - restore_cache:
          keys:
            - pip-packages-v11-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: url
          command: pytest ./tests/test_url.py

  test-s3:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo chown -R circleci /usr/local
      # use the saved cache from the build to avoid reinstalling the libs
      - restore_cache:
          keys:
            - pip-packages-v11-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: s3
          command: pytest ./tests/test_s3.py

  test-server:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run: sudo chown -R circleci /usr/local
      # use the saved cache from the build to avoid reinstalling the libs
      - restore_cache:
          keys:
            - pip-packages-v11-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: sudo mkdir /DATA
      - run: sudo chmod a+rw /DATA  
      - run:
          name: server
          command: pytest ./tests/test_server.py

workflows:
  version: 2
  tests:
    jobs:
      - build
      - test-sklearn:
          requires:
            - build
      - test-datalad:
          requires:
            - build
      - test-gzip:
          requires:
            - build
      - test-multiple:
          requires:
            - build
      - test-url:
          requires:
            - build
      - test-s3:
          requires:
            - build
      - test-server:
          requires:
            - build
